### ISSUE TITLE
Loss of type information

### ISSUE THREAD

**Issue by akinsho** [tjdevries/lazy.nvim#1]
Hi, thanks for sharing this 👍🏿. They are a really helpful set of functions.

One downside I can't currently see a way round, is that using `sumneko` lsp you lose type information from the requires in this function. So despite documenting and annotating a module in detail all that information is lost, so contributors using the lua lsp would just get any as the type of the module.

I couldn't find anything in https://github.com/sumneko/lua-language-server/wiki/EmmyLua-Annotations but before potentially raising an issue there I wonder if you're aware of a way to annotate things that might pass the information through 🤔 or maybe due to the structure of the function that's not really possible at all to know. Maybe this can only really be solved at the lsp level.

I found one related issues:
* https://github.com/sumneko/lua-language-server/issues/286

**Comment by tjdevries** [comment]
Yeah, I'd have to check that out for sumneko, this is a good point.

Perhaps something like:

```lua
local require = require("lazy").require_on_index

-- do other things now
local telescope = require('telescope')
```

That might work? I'm not sure what sumneko will do then.

The other option would be if it returns a class, you can specify what the class or object is via emmy lua annotations maybe?

**Comment by akinsho** [comment]
Just gave the `require` alias a shot and sumneko recognizes it as the lazy module function rather than the return of the require. I'll ask on sumneko's repo if there's some way around this and link the issue back here.

**Comment by tjdevries** [comment]
Perfect :) Maybe there is a setting that can be added to lsp configuration or something else that can alias them or a type hint like:

```lua
---@import telescope.path
local path = lazy_require('telescope.path')
```

or similar

**Comment by akinsho** [comment]
A fix for this got merged upstream in sumneko ❤️  https://github.com/sumneko/lua-language-server/commit/e44142d13914bc98a4f9af0029cfadbc16e222a4

You can now do 
```lua
---@module 'telescope.path'
local path = lazy_require('telescope.path')
```
